### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by Semyon-O** [vkokarev-23/module_2#1]
Добрый день. В целом решении интересное, но есть косяки, недочеты и плюсы:

Начну с хорошего:
- Очень здорово что вы решили разбить логику на функции. Причем подобрали в некоторых местах хорошие места логики вынесения.
- Приятно, что ввести несколько раз числа. А не перезапускать программу

Недочеты:
- Функции - это хорошо, НО. Функции очень НЕЖЕЛАТЕЛЬНО обращать к переменной, которая выше, потому что в некоторых местах - это можем приносить ошибки. Рекомендую прочитать статьи про локальные, глобальные переменные, чтобы понять  в чем мое возмущение.
- В принципе логику очень хорошо, что вынесли за функции. Но кое-где вы перестарались, а именно здесь:
```py
def clear_stone_pair():
    stone_pair.clear()
```
Создавать такую функцию, особо нету смысла, ибо она имеет всего лишь одно действие. 

Косяки:
- По Задаче вам нужно выводить пароль, вы же на данный момент, просто выводите подходящую сумму чисел:
![изображение](https://github.com/user-attachments/assets/cfbbd940-c7e5-4efc-bd9b-06f63e8611e6)

Это немного не то, что требуется в задаче. Нужно вывести итоговый пароль, а не набор сумм чисел кратных цифре.

**Comment by vkokarev-23** [comment]
Функция def clear_stone_pair(): ранее выполняла отладочную печать до и после очистки списка. Ушла отладка - потерялся смысл в такой функции.

По-прежнему не чувствую ущербности в изменении глобальных переменных в функции. И как это сделать иначе? Передавать список в качестве параметра, а измененный получать в виде значения? Так лучше?

PyCharm ругается на меня (shadows name from outer scope), если я использую одинаковые имена переменных " i " в глобальном и локальном пространстве имен. А как иначе? Ведь " i " так удобно.
